version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: image.Dockerfile
      target: php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8066:8080"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailpit:
        condition: service_healthy
    volumes:
      - app-storage:/var/www/storage
      - ./docker/entrypoint.ci.sh:/var/www/docker/entrypoint.sh
    command: sh -c /var/www/docker/entrypoint.sh && exit

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost

  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
    command: redis-server --appendonly yes --requirepass  "secret"
    ports:
      - "6380:6379"

  mailpit:
    image: axllent/mailpit
    healthcheck:
      test: /usr/bin/nc -v localhost 1025
      interval: 30s
    ports:
      - "48025:8025"
      - "41025:1025"

volumes:
  db-data:
  app-storage:
