<?php

namespace App\Exceptions;

use App\Enums\Errors\CommonError;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\JsonResponse;
use Illuminate\Validation\ValidationException;
use Laravel\Sanctum\Exceptions\MissingAbilityException;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    /**
     * Render an exception into an HTTP response.
     *
     *
     * @link https://github.com/riandyrn/remindme-laravel/blob/main/docs/common_errors.md
     * @link https://github.com/riandyrn/remindme-laravel/blob/3f565565ca94205cffe01d3827c0478a1ae9db4c/docs/rest_api.md?plain=1#L81
     * @link https://github.com/riandyrn/remindme-laravel/blob/3f565565ca94205cffe01d3827c0478a1ae9db4c/docs/rest_api.md?plain=1#L133
     *
     * @param \Illuminate\Http\Request $request
     * @param \Throwable $e
     * @return \Illuminate\Http\Response|JsonResponse
     *
     * @throws \Throwable
     */
    public function render($request, Throwable $e)
    {
        if ($e instanceof AccessDeniedHttpException || $e instanceof MissingAbilityException) {
            $forbidden = CommonError::ERR_FORBIDDEN_ACCESS;

            return response()->json([
                'ok' => false,
                'error' => $forbidden->value,
                'msg' => $forbidden->message()
            ], $forbidden->httpStatusCode());
        }

        if ($e instanceof \Illuminate\Auth\AuthenticationException) {
            $error = CommonError::ERR_INVALID_ACCESS_TOKEN;

            return response()->json($error->toMap(), $error->httpStatusCode());
        }

        if ($e instanceof ValidationException) {
            $error = CommonError::ERR_BAD_REQUEST;

            return response()->json($error->toMap($e->getMessage()), $error->httpStatusCode());
        }

        if ($this->isHttpException($e)) {
            $error = CommonError::createFromHttpStatusCode($e->getStatusCode());

            if (filled($error)) {
                return \response()->json($error->toMap(), $error->httpStatusCode());
            }

            return \response()->json([
                'ok' => false,
                'err' => 'HTTP_HANDLER',
                'msg' => $e->getMessage()
            ], $e->getStatusCode());
        }

        return \response()->json([
            'status' => 500,
            "err" => CommonError::ERR_INTERNAL_ERROR->value,
            'msg' => $e->getMessage()
        ], 500);


        /**
         * !!! Warning !!!
         * If in the future, Nabitu only requests the Accept application/json header, then all the code above will be included in this if block.
         *
         * if ($request->wantsJson()) {
         * }
         *
         * return parent::render($request, $e); // TODO: Change the autogenerated stub
         * */
    }
}
