name: Laravel Deployment

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Your SSH step
      - name: Run sshpass commands
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
          user: ${{ secrets.DEPLOYMENT_SERVER_USER }}
          pass: ${{ secrets.DEPLOYMENT_SERVER_PASSWORD }}
          run: |
            cd remindme-laravel
            git pull
            docker compose -f docker-compose.prod.yml up --build -d
            docker compose ps
            echo "Deploy succeeded!"