name: Laravel Deployment

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env
        working-directory: src
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --no-interaction

      - name: Generate application key
        run: php artisan key:generate

      - name: Install sshpass for login with password in ssh
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to production
        env:
          SSH_USER: ${{ secrets.DEPLOYMENT_SERVER_USER }}
          SSH_HOST: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
          SSH_PASSWORD: ${{ secrets.DEPLOYMENT_SERVER_PASSWORD }}
        run: |
          sshpass -p $SSH_PASSWORD ssh $SSH_USER@$SERVER_IP  "cd /var/www/html/remindme && \
          git pull origin main && \
          composer install --no-dev --prefer-dist --no-interaction && \
          php artisan migrate --force && \
          php artisan route:cache && \
          php artisan view:cache && \
          php artisan config:cache && \
          php artisan optimize"