name: Laravel Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.DEPLOYMENT_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy ke Produksi
        env:
          SSH_USER: ${{ secrets.DEPLOYMENT_SERVER_USER }}
          SSH_HOST: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST "cd remindme-laravel&& \
          git pull && \
          docker compose build -f docker-compose.prod.yml --no-cache"