name: Laravel Deployment

# see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
on:
  push:
    branches:
      - main

jobs:
  deploy-via-sshpass:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run sshpass commands
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
          user: ${{ secrets.DEPLOYMENT_SERVER_USER }}
          pass: ${{ secrets.DEPLOYMENT_SERVER_PASSWORD }}
          run: |
            cd remindme-laravel
            git pull
            docker compose -f docker-compose.prod.yml up --build -d
            docker compose ps
            echo "Deploy succeeded!"